### ISSUE TITLE
Remove CFDP PDU introspection features

### ISSUE THREAD

**Issue by avan989** [nasa/ci_lab#27]
**Is your feature request related to a problem? Please describe.**
CFDP PDU introspection is old debug code.  Remove to simplify ci_lab.

Also subject of recommended issues from lgtm:

ci_lab_app.c
```
line 625 - 732:
Switch has at least one case that is too long: 4 (37 lines)

line 599:

/*    OS_printf("CI: Captured PDU with length = %d\n",PduHdrPtr->PDataLen); */
--
  | This comment appears to contain commented-out code

```

**Requester Info**
Anh Van, NASA Goddard

**Comment by jphickey** [comment]
That chunk of code has been discussed in the past - it is related to some CFDP PDU introspection which seems to be some debug stuff that somehow made it into the framework baseline.

IIRC it was agreed on at least one occasion that this should be removed because nobody uses it, nobody tests it, it doesn't have a requirement, and isn't cross-platform compatible.

I recommend removing the entire `CI_ProcessPDU` function and all commands associated with the CFDP PDU introspection "feature" of CI LAB.

**Comment by skliper** [comment]
Concur.  Hijacking this ticket, now more general to address removing CFDP PDU introspection features.

**Comment by jphickey** [comment]
Taking this ticket because some of this PDU stuff is getting in the way of another change.
