### ISSUE TITLE
Refactor ingest to utilize zero copy (can reduce two copy to one)

### ISSUE THREAD

**Issue by skliper** [nasa/ci_lab#73]
**Is your feature request related to a problem? Please describe.**
CI copies the data into a local buffer and then uses CFE_SB_TransmitMsg (which does a second copy into the SB buffer):
https://github.com/nasa/ci_lab/blob/296d12cde4f90d112d1578cb584ddae200a2d282/fsw/src/ci_lab_app.c#L359-L374

**Describe the solution you'd like**
Could use zero copy to get a buffer, write directly to the buffer and CFE_SB_TransmitBuffer (single copy)

**Describe alternatives you've considered**
None

**Additional context**
We don't have a functional example of zero copy, just documentation.  This would support user request for a working example as well as improve performance.

**Requester Info**
Jacob Hageman - NASA/GSFC (from stakeholder request)

**Comment by jphickey** [comment]
I actually like the fact that this copies the packet, because CI/TO should someday take on the role of dealing with the differences between network encoding/padding and native encoding/padding.

That is, the "dumb" memcpy that is done now can be replaced with a "smart" endian- and padding- aware copy.  It is the ideal place to do this because its transparent to all apps.

I don't want to re-open culture wars on the subject - even if some users don't want to do it this way for some reason - I'm just saying its a valid and useful option to have, and it works well (speaking from experience).

**Comment by jphickey** [comment]
After thinking about this for another minute - it's probably fine either way because even in the "smart" CI/TO copy case it can still use the zero copy method to send the message on once its been fixed up.

However - we do need to coordinate this with nasa/cfe#1155.  That one is waiting right behind the reorganization stuff in nasa/cfe#1203.
